'use strict';

const { onRequest } = require('firebase-functions/v2/https');
const { getFirebaseAdmin } = require('../config/firebase');
const { AppError, handleError } = require('../utils/errors');
const { COLLECTIONS, AUDIT_ACTIONS } = require('../constants/collections');
const { writeAuditLog } = require('../utils/audit');
const { isValidUid } = require('../utils/validation');
const { generateTemporaryPassword } = require('../utils/temporaryPassword');

const ADMIN_IMPORT_KEY = process.env.ADMIN_IMPORT_KEY || 'ced-admin-import-2026';

function requireAdminKey(req) {
  if (req.get('x-admin-key') !== ADMIN_IMPORT_KEY) {
    throw new AppError('Unauthorized.', 401, 'UNAUTHORIZED');
  }
}

// POST /regenerateScholarPassword { targetUid }
// Re-derives the scholar's temp password from their CURRENT lastName +
// grantSchoolYear (already on their doc) and sets it as their real Auth
// password, forcing a change again on next login.
exports.regenerateScholarPassword = onRequest({ cors: true }, async (req, res) => {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  try {
    requireAdminKey(req);
    const { targetUid } = req.body || {};
    if (!targetUid || !isValidUid(targetUid)) throw new AppError('Invalid targetUid.', 400, 'INVALID_UID');

    const { auth, db } = getFirebaseAdmin();
    const docSnap = await db.collection(COLLECTIONS.USERS).doc(targetUid).get();
    if (!docSnap.exists) throw new AppError('Scholar not found.', 404, 'NOT_FOUND');
    const data = docSnap.data();

    const password = generateTemporaryPassword(data.lastName, data.grantSchoolYear || '2026-2027');
    await auth.updateUser(targetUid, { password });
    await docSnap.ref.update({ mustChangePassword: true });

    await writeAuditLog(db, {
      userId: 'admin-import', userRole: 'admin', action: AUDIT_ACTIONS.PASSWORD_RESET,
      collection: COLLECTIONS.USERS, documentId: targetUid, details: 'Temporary password regenerated by admin',
    });

    return res.json({ success: true, password });
  } catch (err) {
    return handleError(res, err, 'regenerateScholarPassword');
  }
});

// POST /setScholarAccountDisabled { targetUid, disabled }
// Firebase Auth's own `disabled` flag is the source of truth (Auth rejects
// sign-in for a disabled account natively); mirrored into Firestore only so
// the admin UI can filter Active/Disabled lists without a separate Auth call.
exports.setScholarAccountDisabled = onRequest({ cors: true }, async (req, res) => {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  try {
    requireAdminKey(req);
    const { targetUid, disabled } = req.body || {};
    if (!targetUid || !isValidUid(targetUid)) throw new AppError('Invalid targetUid.', 400, 'INVALID_UID');

    const { auth, db } = getFirebaseAdmin();
    const docSnap = await db.collection(COLLECTIONS.USERS).doc(targetUid).get();
    if (!docSnap.exists) throw new AppError('Scholar not found.', 404, 'NOT_FOUND');

    const shouldDisable = disabled !== false;
    await auth.updateUser(targetUid, { disabled: shouldDisable });
    await docSnap.ref.update({ accountDisabled: shouldDisable });

    await writeAuditLog(db, {
      userId: 'admin-import', userRole: 'admin', action: AUDIT_ACTIONS.UPDATE,
      collection: COLLECTIONS.USERS, documentId: targetUid,
      details: `Account ${shouldDisable ? 'disabled' : 're-enabled'} by admin`,
    });

    return res.json({ success: true });
  } catch (err) {
    return handleError(res, err, 'setScholarAccountDisabled');
  }
});
